hw3_flat:
	g++ flat.cpp helper.cpp helper.h -std=c++11 -O3 -o hw3_flat -lXi -lGLEW -lGLU -lGL -lm -lpthread -ldrm -lXdamage -lX11-xcb -lxcb-glx -lxcb-dri2 -lglfw3 -lrt -ldl -lXrandr -lXinerama -lXxf86vm -lXext -lXcursor -lXrender -lXfixes -lX11 -lpthread -lxcb -lXau -lXdmcp -ljpeg

hw3_sphere:
	g++ sphere.cpp sphereHelper.cpp sphereHelper.h -std=c++11 -O3 -o hw3_sphere -lXi -lGLEW -lGLU -lGL -lm -lpthread -ldrm -lXdamage -lX11-xcb -lxcb-glx -lxcb-dri2 -lglfw3 -lrt -ldl -lXrandr -lXinerama -lXxf86vm -lXext -lXcursor -lXrender -lXfixes -lX11 -lpthread -lxcb -lXau -lXdmcp -ljpeg

